name: Unity CI

on:
  pull_request:
    branches:
      - main  # or the branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: '2021.3.0f1'  # Set to your Unity version

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: '2021.3.0f1'  # Set to your Unity version

      - name: Run StyleCop
        run: |
          dotnet tool install --global dotnet-format
          dotnet-format --check --verbosity minimal
        env:
          DOTNET_ROOT: /usr/share/dotnet/sdk  # Ensure .NET SDK path is set

  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run AI-supported code analysis
        uses: deepsource/[tool-name]  # Replace with appropriate tool action
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}  # DeepSource DSN for analysis
